version: "2"

formatters:
  enable:
    - gci
    - gofumpt
    - golines
  settings:
    gci:
      section_order:
        - Standard
        - Default
        - localmodules
        - alias
        - blank
        - dot
      custom_order: true
    gofumpt:
      extra_rules: true
    golines:
      max_len: 120

linters:
  default: standard
