version: "2"

formatters:
  enable:
    - gci
    - gofumpt
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
        - alias
        - blank
        - dot
      custom-order: true
    gofumpt:
      extra-rules: true
    golines:
      max-len: 120

linters:
  default: standard
